name: 'yaml-parser'
description: 'Simple YAML parser for Github Action'
author: 'Kyungmin Lee'
inputs:
  file:
    required: true
    description: 'file path'
runs:
  using: 'node16'
  main: 'dist/index.js'
